name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Prepare release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Build ${{ github.job }}"
          tag_name: "Build ${{ github.job }}"
          #body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - id: step_upload_url
        name: Set Release Upload URL for proceeding steps
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"

  build_web:
    name: Build Web Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Get Flutter Packages
        run: flutter pub get
      
      - name: Build Flutter Web
        run: flutter build web
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
          
  build_apk:
    name: Build Android Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Java Setup (?)
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
    
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
          
      - name: Get Flutter Packages
        run: flutter pub get
      
      - name: Build Flutter APK
        run: flutter build apk
      
      - name: upload APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.prepare_release.outputs.upload_url }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: android-release.apk
          asset_content_type: application/zip